else if (IsPrefixOrEqual(pdb, "hwrena")) stpcpy(mdb, "print /d HWREna\n");
else if (IsPrefixOrEqual(pdb, "badvaddr")) stpcpy(mdb, "print /d BadVAddr\n");
else if (IsPrefixOrEqual(pdb, "count")) stpcpy(mdb, "print /d Count\n");
else if (IsPrefixOrEqual(pdb, "compare")) stpcpy(mdb, "print /d Compare\n");
else if (IsPrefixOrEqual(pdb, "status")) stpcpy(mdb, "print /d Status\n");
else if (IsPrefixOrEqual(pdb, "intctl")) stpcpy(mdb, "print /d IntCtl\n");
else if (IsPrefixOrEqual(pdb, "srsctl")) stpcpy(mdb, "print /d SRSCtl\n");
else if (IsPrefixOrEqual(pdb, "srsmap")) stpcpy(mdb, "print /d SRSMap\n");
else if (IsPrefixOrEqual(pdb, "view_ipl")) stpcpy(mdb, "print /d View_IPL\n");
else if (IsPrefixOrEqual(pdb, "srsmap2")) stpcpy(mdb, "print /d SRSMap2\n");
else if (IsPrefixOrEqual(pdb, "cause")) stpcpy(mdb, "print /d Cause\n");
else if (IsPrefixOrEqual(pdb, "view_ripl")) stpcpy(mdb, "print /d View_RIPL\n");
else if (IsPrefixOrEqual(pdb, "epc")) stpcpy(mdb, "print /d EPC\n");
/* else if (IsPrefixOrEqual(pdb, "prid")) stpcpy(mdb, "print /d PRID/Prid/prid\n"); */
else if (IsPrefixOrEqual(pdb, "ebase")) stpcpy(mdb, "print /d EBase\n");
else if (IsPrefixOrEqual(pdb, "cdmmbase")) stpcpy(mdb, "print /d CDMMBase\n");
else if (IsPrefixOrEqual(pdb, "config\n")) stpcpy(mdb, "print /d Config\n");
else if (IsPrefixOrEqual(pdb, "config1")) stpcpy(mdb, "print /d Config1\n");
else if (IsPrefixOrEqual(pdb, "config3")) stpcpy(mdb, "print /d Config3\n");
else if (IsPrefixOrEqual(pdb, "config7")) stpcpy(mdb, "print /d Config7\n");
else if (IsPrefixOrEqual(pdb, "debug\n")) stpcpy(mdb, "print /d Debug\n");
else if (IsPrefixOrEqual(pdb, "tracecontrol\n")) stpcpy(mdb, "print /d TraceControl\n");
else if (IsPrefixOrEqual(pdb, "tracecontrol2")) stpcpy(mdb, "print /d TraceControl2\n");
/* else if (IsPrefixOrEqual(pdb, "usertracedata1")) stpcpy(mdb, "print /d UserTraceData1\n"); */
else if (IsPrefixOrEqual(pdb, "tracebpc")) stpcpy(mdb, "print /d TraceBPC\n");
else if (IsPrefixOrEqual(pdb, "debug2")) stpcpy(mdb, "print /d Debug2\n");
else if (IsPrefixOrEqual(pdb, "depc")) stpcpy(mdb, "print /d Depc\n");
else if (IsPrefixOrEqual(pdb, "usertracedata2")) stpcpy(mdb, "print /d UserTraceData2\n");
else if (IsPrefixOrEqual(pdb, "perfctl0")) stpcpy(mdb, "print /d PerfCtl0\n");
else if (IsPrefixOrEqual(pdb, "perfcnt0")) stpcpy(mdb, "print /d PerfCnt0\n");
else if (IsPrefixOrEqual(pdb, "perfctl1")) stpcpy(mdb, "print /d PerfCtl1\n");
else if (IsPrefixOrEqual(pdb, "perfcnt1")) stpcpy(mdb, "print /d PerfCnt1\n");
else if (IsPrefixOrEqual(pdb, "errctl")) stpcpy(mdb, "print /d ErrCtl\n");
else if (IsPrefixOrEqual(pdb, "cacheerr")) stpcpy(mdb, "print /d CacheErr\n");
else if (IsPrefixOrEqual(pdb, "desave")) stpcpy(mdb, "print /d DeSave\n");
else if (IsPrefixOrEqual(pdb, "intcon")) stpcpy(mdb, "print /d intcon\n");
else if (IsPrefixOrEqual(pdb, "priss")) stpcpy(mdb, "print /d priss\n");
else if (IsPrefixOrEqual(pdb, "intstat")) stpcpy(mdb, "print /d intstat\n");
else if (IsPrefixOrEqual(pdb, "iptmr")) stpcpy(mdb, "print /d iptmr\n");
else if (IsPrefixOrEqual(pdb, "ifs\n")) stpcpy(mdb, "print /d ifs0\nprint /d ifs1\nprint /d ifs2\nprint /d ifs3\nprint /d ifs4\nprint /d ifs5\nprint /d ifs6\n");
else if (IsPrefixOrEqual(pdb, "iec\n")) stpcpy(mdb, "print /d iec0\nprint /d iec1\nprint /d iec2\nprint /d iec3\nprint /d iec4\nprint /d iec5\nprint /d iec6\n");
else if (IsPrefixOrEqual(pdb, "ifs0")) stpcpy(mdb, "print /d ifs0\n");
else if (IsPrefixOrEqual(pdb, "ifs1")) stpcpy(mdb, "print /d ifs1\n");
else if (IsPrefixOrEqual(pdb, "iec0")) stpcpy(mdb, "print /d iec0\n");
else if (IsPrefixOrEqual(pdb, "iec1")) stpcpy(mdb, "print /d iec1\n");
else if (IsPrefixOrEqual(pdb, "ipc0")) stpcpy(mdb, "print /d ipc0\n");
else if (IsPrefixOrEqual(pdb, "ipc1")) stpcpy(mdb, "print /d ipc1\n");
else if (IsPrefixOrEqual(pdb, "ipc2")) stpcpy(mdb, "print /d ipc2\n");
else if (IsPrefixOrEqual(pdb, "ipc3")) stpcpy(mdb, "print /d ipc3\n");
else if (IsPrefixOrEqual(pdb, "ipc4")) stpcpy(mdb, "print /d ipc4\n");
else if (IsPrefixOrEqual(pdb, "ipc5")) stpcpy(mdb, "print /d ipc5\n");
else if (IsPrefixOrEqual(pdb, "ipc6")) stpcpy(mdb, "print /d ipc6\n");
else if (IsPrefixOrEqual(pdb, "ipc7")) stpcpy(mdb, "print /d ipc7\n");
else if (IsPrefixOrEqual(pdb, "ipc8")) stpcpy(mdb, "print /d ipc8\n");
else if (IsPrefixOrEqual(pdb, "ipc9")) stpcpy(mdb, "print /d ipc9\n");
else if (IsPrefixOrEqual(pdb, "ipc10")) stpcpy(mdb, "print /d ipc10\n");
else if (IsPrefixOrEqual(pdb, "ipc11")) stpcpy(mdb, "print /d ipc11\n");
else if (IsPrefixOrEqual(pdb, "osccon")) stpcpy(mdb, "print /d osccon\n");
else if (IsPrefixOrEqual(pdb, "spllcon")) stpcpy(mdb, "print /d spllcon\n");
else if (IsPrefixOrEqual(pdb, "refo1con")) stpcpy(mdb, "print /d refo1con\n");
else if (IsPrefixOrEqual(pdb, "refo1trim")) stpcpy(mdb, "print /d refo1trim\n");
else if (IsPrefixOrEqual(pdb, "clkstat")) stpcpy(mdb, "print /d clkstat\n");
else if (IsPrefixOrEqual(pdb, "osctun")) stpcpy(mdb, "print /d osctun\n");
else if (IsPrefixOrEqual(pdb, "a\n")) stpcpy(mdb, "print /d porta\nprint /d lata\nprint /d trisa\n");
else if (IsPrefixOrEqual(pdb, "b\n")) stpcpy(mdb, "print /d portb\nprint /d latb\nprint /d trisb\n");
else if (IsPrefixOrEqual(pdb, "c\n")) stpcpy(mdb, "print /d portc\nprint /d latc\nprint /d trisc\n");
else if (IsPrefixOrEqual(pdb, "rpcon")) stpcpy(mdb, "print /d rpcon\n");
else if (IsPrefixOrEqual(pdb, "rpinr1")) stpcpy(mdb, "print /d rpinr1\n");
else if (IsPrefixOrEqual(pdb, "rpinr3")) stpcpy(mdb, "print /d rpinr3\n");
else if (IsPrefixOrEqual(pdb, "rpinr2")) stpcpy(mdb, "print /d rpinr2\n");
else if (IsPrefixOrEqual(pdb, "rpinr5")) stpcpy(mdb, "print /d rpinr5\n");
else if (IsPrefixOrEqual(pdb, "rpinr6")) stpcpy(mdb, "print /d rpinr6\n");
else if (IsPrefixOrEqual(pdb, "rpinr9")) stpcpy(mdb, "print /d rpinr9\n");
else if (IsPrefixOrEqual(pdb, "rpinr11")) stpcpy(mdb, "print /d rpinr11\n");
else if (IsPrefixOrEqual(pdb, "rpinr12")) stpcpy(mdb, "print /d rpinr12\n");
else if (IsPrefixOrEqual(pdb, "rpor0")) stpcpy(mdb, "print /d rpor0\n");
else if (IsPrefixOrEqual(pdb, "rpor1")) stpcpy(mdb, "print /d rpor1\n");
else if (IsPrefixOrEqual(pdb, "rpor2")) stpcpy(mdb, "print /d rpor2\n");
else if (IsPrefixOrEqual(pdb, "rpor3")) stpcpy(mdb, "print /d rpor3\n");
else if (IsPrefixOrEqual(pdb, "rpor4")) stpcpy(mdb, "print /d rpor4\n");
else if (IsPrefixOrEqual(pdb, "t1con")) stpcpy(mdb, "print /d t1con\n");
else if (IsPrefixOrEqual(pdb, "tmr1")) stpcpy(mdb, "print /d tmr1\n");
else if (IsPrefixOrEqual(pdb, "pr1")) stpcpy(mdb, "print /d pr1\n");
else if (IsPrefixOrEqual(pdb, "wdtcon")) stpcpy(mdb, "print /d wdtcon\n");
/* ... */
else if (IsPrefixOrEqual(pdb, "spi1con")) stpcpy(mdb, "print /d spi1con\n");
else if (IsPrefixOrEqual(pdb, "spi1stat")) stpcpy(mdb, "print /d spi1stat\n");
else if (IsPrefixOrEqual(pdb, "spi1buf")) stpcpy(mdb, "print /d spi1buf\n");
else if (IsPrefixOrEqual(pdb, "spi1brg")) stpcpy(mdb, "print /d spi1brg\n");
else if (IsPrefixOrEqual(pdb, "spi1con2")) stpcpy(mdb, "print /d spi1con2\n");
else if (IsPrefixOrEqual(pdb, "spi2con")) stpcpy(mdb, "print /d spi2con\n");
else if (IsPrefixOrEqual(pdb, "spi2stat")) stpcpy(mdb, "print /d spi2stat\n");
else if (IsPrefixOrEqual(pdb, "spi2buf")) stpcpy(mdb, "print /d spi2buf\n");
else if (IsPrefixOrEqual(pdb, "spi2brg")) stpcpy(mdb, "print /d spi2brg\n");
else if (IsPrefixOrEqual(pdb, "spi2con2")) stpcpy(mdb, "print /d spi2con2\n");
else if (IsPrefixOrEqual(pdb, "u1mode")) stpcpy(mdb, "print /d u1mode\n");
else if (IsPrefixOrEqual(pdb, "u1sta")) stpcpy(mdb, "print /d u1sta\n");
else if (IsPrefixOrEqual(pdb, "u1txreg")) stpcpy(mdb, "print /d u1txreg\n");
else if (IsPrefixOrEqual(pdb, "u1rxreg")) stpcpy(mdb, "print /d u1rxreg\n");
else if (IsPrefixOrEqual(pdb, "u1brg")) stpcpy(mdb, "print /d u1brg\n");
else if (IsPrefixOrEqual(pdb, "u2mode")) stpcpy(mdb, "print /d u2mode\n");
else if (IsPrefixOrEqual(pdb, "u2sta")) stpcpy(mdb, "print /d u2sta\n");
else if (IsPrefixOrEqual(pdb, "u2txreg")) stpcpy(mdb, "print /d u2txreg\n");
else if (IsPrefixOrEqual(pdb, "u2rxreg")) stpcpy(mdb, "print /d u2rxreg\n");
else if (IsPrefixOrEqual(pdb, "u2brg")) stpcpy(mdb, "print /d u2brg\n");
else if (IsPrefixOrEqual(pdb, "adc1")) stpcpy(mdb, "print /d adc1buf0\nprint /d adc1buf1\nprint /d adc1buf2\nprint /d adc1buf3\nprint /d adc1buf4\nprint /d adc1buf5\nprint /d adc1buf6\nprint /d adc1buf7\nprint /d adc1buf8\nprint /d adc1buf9\nprint /d adc1buf10\nprint /d adc1buf11\nprint /d adc1buf12\nprint /d adc1buf13\nprint /d adc1buf14\nprint /d adc1buf15\n");
else if (IsPrefixOrEqual(pdb, "ad1con")) stpcpy(mdb, "print /d ad1con1\nprint /d ad1con2\nprint /d ad1con3\nprint /d ad1con5\n");
else if (IsPrefixOrEqual(pdb, "ad1chs")) stpcpy(mdb, "print /d ad1chs\n");
else if (IsPrefixOrEqual(pdb, "ad1css")) stpcpy(mdb, "print /d ad1css\n");
else if (IsPrefixOrEqual(pdb, "ad1chit")) stpcpy(mdb, "print /d ad1chit\n");
else if (IsPrefixOrEqual(pdb, "cmstat")) stpcpy(mdb, "print /d cmstat\n");
else if (IsPrefixOrEqual(pdb, "cm1con")) stpcpy(mdb, "print /d cm1con\n");
else if (IsPrefixOrEqual(pdb, "cm2con")) stpcpy(mdb, "print /d cm2con\n");
else if (IsPrefixOrEqual(pdb, "dac1con")) stpcpy(mdb, "print /d dac1con\n");
else if (IsPrefixOrEqual(pdb, "hlvdcon")) stpcpy(mdb, "print /d hlvdcon\n");


